### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by johanneskoester** [christopher-schroeder/rust-htslib#1]
Hi,
the docs should be linked in the readme. Actually, I cannot seem to access them via http://christopher-schroeder.github.io/rust-htslib. Are the github pages set up via the settings dialog?

Have a nice weekend ;-)!

**Comment by christopher-schroeder** [comment]
the generated docs are linked, i'm not sure if its the correct structure, but it works

**Comment by johanneskoester** [comment]
Looks perfect!
